apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: ai
spec:
  replicas: 1 # 보통 1개만 실행 (필요하면 여러 개 가능)
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-3
      imagePullSecrets:
        - name: ai-ecr-secret # ECR 로그인 Secret
      containers:
        - name: airflow-scheduler
          image: 941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/ai:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ai-config # ConfigMap 환경 변수 로드
            - secretRef:
                name: ai-secret # Secret 환경 변수 로드
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting Airflow Scheduler..."
              airflow db upgrade  # DB 마이그레이션 (최신 상태 유지)
              exec airflow scheduler  # Scheduler 실행
