apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-3
      imagePullSecrets:
        - name: ai-ecr-secret
      containers:
        - name: airflow-webserver
          image: 941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/ai:latest
          imagePullPolicy: Always
          command: ["/entrypoint-webserver.sh"]
          args: ["--port", "8080"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ai-config
            - secretRef:
                name: ai-secret

---

apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-svc
  namespace: ai
spec:
  selector:
    app: airflow-webserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
