apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-3
      imagePullSecrets:
        - name: ai-ecr-secret
      containers:
        - name: airflow-webserver
          image: ""
          imagePullPolicy: Always
          command: ["airflow", "webserver"]
          args: ["--port", "8080"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ai-config
            - secretRef:
                name: ai-secret
                # env:
                #   - name: DB_PASSWORD
                #     valueFrom:
                #       secretKeyRef:
                #         name: ai-secret
                #         key: DB_PASSWORD
                #   - name: CRYPTOPANIC_API_KEY
                #     valueFrom:
                #       secretKeyRef:
                #         name: ai-secret
                #         key: CRYPTOPANIC_API_KEY
                #   - name: OPENAI_API_KEY
                #     valueFrom:
                #       secretKeyRef:
                #         name: ai-secret
                #         key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-svc
  namespace: ai
spec:
  selector:
    app: airflow-webserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP # 혹은 NodePort
  template:
    spec:
      containers:
        - image: ""
